[package]
name = "roboclaw"
version = "0.1.0"
authors = ["Marek Miettinen <marek.miettinen@gmail.com>"]
description = "Roboclaw DC motor controller"
license = "MIT"
edition = "2018"
categories = ["hardware-support"]
keywords = ["roboclaw", "basicmicro", "motor"]
readme = "README.md"
documentation = "https://github.com/marikka/roboclaw-rs"
homepage = "https://github.com/marikka/roboclaw-rs"
repository = "https://github.com/marikka/roboclaw-rs"

[[bin]]
name = "roboclaw-gui"
path = "src/bin/gui.rs"

[dependencies]
serial = "0.4"
crc16 = "0.4.0"
bitflags = "1.0.4"
eframe = "0.24"
egui = "0.24"
serde = { version = "1.0", features = ["derive"] }